process.on("exit", ()=>{
    console.log('La aplicaciÃ³n finalizo')
})
process.on("uncaughtException", (error, origin)=>{
    console.log(`Hubo un error: ${error} ${origin}`);
})

funcionQueNoExiste();